spring.application.name=student-service


spring.data.mongodb.uri=mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@cluster0.fborwqk.mongodb.net/${MONGODB_BASS}?retryWrites=true&w=majority&appName=Cluster0
